require:
  - rubocop-performance
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - micropub-endpoint.gemspec
    - spec/**/*.rb

Metrics/LineLength:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
